<?php
require_once __DIR__ . '/../../includes/config.php';

$article = [
  'slug' => 'ai-agent-instruction-files-explained',
  'title' => 'AI Agent Instruction Files Explained',
  'seo_title' => 'AI Agent Instruction Files: Every .md File | Markdown Docs',
  'description' => 'A complete guide to AI agent instruction files: README, AGENTS, CLAUDE, GEMINI, Cursor, Copilot, Windsurf, CONVENTIONS, and llms.txt, and when to use each.',
  'date' => '2026-06-13',
  'reading_time' => '10 min read',
  'eyebrow' => 'AI agent files pillar guide',
  'h1' => 'AI agent instruction files explained',
  'lead' => 'AI coding agents read Markdown files to learn how your project works. This guide covers every common .md and rules file, what it does, and when to use it.',
  'sections' => [
    ['heading' => 'What are AI agent instruction files?', 'body' => '<p>AI agent instruction files are Markdown documents that give AI coding tools persistent context about a project: how to build it, the coding style to follow, which files matter, and what not to touch. Tools load them automatically at the start of a session, so the assistant begins each task already knowing your rules instead of guessing from the surrounding code.</p><p>They are plain Markdown on purpose. Markdown is compact, token-efficient, version-controls cleanly in Git, and is readable by both people and models. That is why nearly every AI coding tool now standardizes on a Markdown instruction file.</p>'],
    ['heading' => 'Why these files exist', 'body' => '<p>Large language models are powerful but stateless. Without context they re-derive your conventions every session and often get them wrong: the wrong test command, the wrong library, a style that does not match the codebase. Instruction files solve this by writing the project rules down once. The result is fewer hallucinations, fewer corrections, and code that fits your project on the first try. Studies of agent files report meaningfully fewer bugs and corrections when a clear file is present.</p>'],
    ['heading' => 'Every AI agent file at a glance', 'body' => '<table><tbody><tr><th>File</th><th>Tool</th><th>Location</th><th>Purpose</th></tr><tr><td><a href="/blog/what-is-readme-md/">README.md</a></td><td>Universal</td><td>Repo root</td><td>Explain the project to humans and give first context</td></tr><tr><td><a href="/blog/what-is-agents-md/">AGENTS.md</a></td><td>Cross-agent</td><td>Repo root</td><td>Open format with build, test, and behavior rules for any agent</td></tr><tr><td><a href="/blog/what-is-claude-md/">CLAUDE.md</a></td><td>Claude Code</td><td>Root or ~/.claude</td><td>Persistent project memory and workflow rules for Claude</td></tr><tr><td><a href="/blog/what-is-gemini-md/">GEMINI.md</a></td><td>Gemini CLI</td><td>Root or ~/.gemini</td><td>Hierarchical context for Google Gemini CLI</td></tr><tr><td><a href="/blog/what-is-copilot-instructions-md/">copilot-instructions.md</a></td><td>GitHub Copilot</td><td>.github/</td><td>Repository-wide custom instructions for Copilot</td></tr><tr><td><a href="/blog/what-are-cursor-rules/">Cursor rules (.mdc)</a></td><td>Cursor</td><td>.cursor/rules/</td><td>Scoped, glob-targeted rules for the Cursor agent</td></tr><tr><td><a href="/blog/what-are-windsurf-rules/">Windsurf rules</a></td><td>Windsurf</td><td>Root / global</td><td>Global and workspace rules for the Cascade agent</td></tr><tr><td><a href="/blog/what-is-conventions-md/">CONVENTIONS.md</a></td><td>Aider, others</td><td>Repo root</td><td>Tool-neutral coding standards and library preferences</td></tr><tr><td><a href="/blog/what-is-design-md/">DESIGN.md</a></td><td>Universal</td><td>Repo root or docs/</td><td>Design intent and architecture decisions behind the code</td></tr><tr><td><a href="/blog/what-is-skill-md/">SKILL.md</a></td><td>Claude Agent Skills</td><td>Skill folder</td><td>Package a reusable capability the agent loads on demand</td></tr><tr><td><a href="/blog/what-is-llms-txt/">llms.txt</a></td><td>AI search engines</td><td>Site root</td><td>Site-level summary so AI models cite the right pages</td></tr></tbody></table><p>Projects also use supporting Markdown files that agents read for context, including <a href="/blog/what-is-changelog-md/">CHANGELOG.md</a>, <a href="/blog/what-is-contributing-md/">CONTRIBUTING.md</a>, <a href="/blog/what-is-todo-md/">TODO.md</a>, <a href="/blog/what-is-prompts-md/">PROMPTS.md</a>, <a href="/blog/what-is-api-md/">API.md</a>, and <a href="/blog/what-is-security-md/">SECURITY.md</a>.</p>'],
    ['heading' => 'README.md: the human front door', 'body' => '<p><a href="/blog/what-is-readme-md/">README.md</a> is the universal starting point. It explains what a project is and how to use it, and AI tools read it first for high-level context. Keep it focused on humans, then push operational detail into the agent files below.</p>'],
    ['heading' => 'AGENTS.md: the cross-agent standard', 'body' => '<p><a href="/blog/what-is-agents-md/">AGENTS.md</a> is an open format that OpenAI introduced for Codex in 2025 and most major tools adopted. It holds setup commands, test rules, code style, and boundaries that agents need but that would clutter a README. If you only adopt one agent file, AGENTS.md gives the widest coverage.</p>'],
    ['heading' => 'Tool-specific memory and rules files', 'body' => '<p>Each major tool also has its own file. <a href="/blog/what-is-claude-md/">CLAUDE.md</a> is Claude Code\'s project memory. <a href="/blog/what-is-gemini-md/">GEMINI.md</a> is Gemini CLI\'s hierarchical context. <a href="/blog/what-is-copilot-instructions-md/">copilot-instructions.md</a> drives GitHub Copilot. <a href="/blog/what-are-cursor-rules/">Cursor rules</a> use scoped `.mdc` files, and <a href="/blog/what-are-windsurf-rules/">Windsurf rules</a> guide the Cascade agent. They share a purpose: tell one tool exactly how to work in your project.</p>'],
    ['heading' => 'CONVENTIONS.md and DESIGN.md: standards and intent', 'body' => '<p><a href="/blog/what-is-conventions-md/">CONVENTIONS.md</a> documents coding standards and library preferences in a tool-neutral way. <a href="/blog/what-is-design-md/">DESIGN.md</a> records the reasoning and architecture behind the code, which helps agents make changes that match the product direction, not just local syntax.</p>'],
    ['heading' => 'llms.txt: instructions at the site level', 'body' => '<p><a href="/blog/what-is-llms-txt/">llms.txt</a> extends the idea from repositories to whole websites. It is a root-level Markdown file that tells AI search engines what a site is about and which pages to reference, supporting AEO and GEO. See also our roundup of <a href="/blog/common-md-files-for-ai-projects/">common .md files for AI projects</a>.</p>'],
    ['heading' => 'Which files should you use?', 'body' => '<p>Start small and add as needed:</p><ol><li>Always: a clear <a href="/blog/what-is-readme-md/">README.md</a>.</li><li>For any agent: add <a href="/blog/what-is-agents-md/">AGENTS.md</a> for build, test, and behavior rules.</li><li>Per tool: add the file your team uses (CLAUDE.md, GEMINI.md, Cursor rules, copilot-instructions.md, or Windsurf rules).</li><li>For standards: add <a href="/blog/what-is-conventions-md/">CONVENTIONS.md</a>; for big decisions, add <a href="/blog/what-is-design-md/">DESIGN.md</a>.</li><li>For your website: publish <a href="/blog/what-is-llms-txt/">llms.txt</a>.</li></ol><p>You do not need every file. Use the ones that match your tools and your project.</p>'],
    ['heading' => 'Best practices for agent files', 'body' => '<ul><li>Be concrete: give exact commands, not vague guidance.</li><li>Keep them short and scannable, and split large rule sets into scoped files.</li><li>Commit them to Git so the whole team gets the same behavior.</li><li>Keep them current; an outdated instruction file is worse than none.</li><li>Avoid duplication: shared rules in AGENTS.md, tool-only tweaks in the tool file.</li></ul>'],
    ['heading' => 'Write and preview your agent files', 'body' => '<p>Every file here is Markdown, so you can draft and preview them in one place. Use the <a href="/editor/">Markdown Docs online editor</a> for a quick live preview, or <a href="/download/">download Markdown Docs</a> to open and edit `.md` files directly on Windows with autosave and a full toolbar.</p>']
  ],
  'sources' => [
    ['label' => 'AGENTS.md open format', 'url' => 'https://agents.md/', 'note' => 'the cross-agent standard.'],
    ['label' => 'Anthropic Claude Code memory docs', 'url' => 'https://docs.anthropic.com/en/docs/claude-code/memory', 'note' => 'for CLAUDE.md.'],
    ['label' => 'Gemini CLI GEMINI.md docs', 'url' => 'https://google-gemini.github.io/gemini-cli/docs/cli/gemini-md.html', 'note' => 'for GEMINI.md.'],
    ['label' => 'GitHub Copilot custom instructions', 'url' => 'https://docs.github.com/copilot/customizing-copilot/adding-custom-instructions-for-github-copilot', 'note' => 'for copilot-instructions.md.']
  ],
  'faqs' => [
    ['What is an AI agent instruction file?', 'It is a Markdown file that gives an AI coding tool persistent project context, such as build commands, code style, and boundaries, loaded automatically each session.'],
    ['Do I need all of these files?', 'No. Start with README.md, add AGENTS.md for broad agent support, then add the tool-specific file your team uses. Add others only when the project needs them.'],
    ['What is the difference between AGENTS.md and CLAUDE.md?', 'AGENTS.md is a cross-agent open format read by many tools. CLAUDE.md is specific to Claude Code. Teams often keep shared rules in AGENTS.md and Claude-only notes in CLAUDE.md.'],
    ['Why are these files written in Markdown?', 'Markdown is compact, token-efficient, easy to diff in Git, and readable by both humans and models, which makes it ideal for feeding context to AI tools.'],
    ['Where do agent files usually live?', 'Most sit at the repository root or in a tool folder like .github or .cursor/rules. llms.txt sits at the website root. Global versions can live in your home directory.']
  ]
];

include __DIR__ . '/../../includes/article-template.php';
