<?php
require_once __DIR__ . '/../../includes/config.php';

$article = [
  'slug' => 'how-to-create-a-skill-md-file',
  'title' => 'How to Create a SKILL.md File',
  'seo_title' => 'How to Create a SKILL.md File | Markdown Docs',
  'description' => 'A step-by-step guide to creating a SKILL.md file: the folder structure, where skills live, how to name a skill, the YAML frontmatter, and a full example.',
  'date' => '2026-06-13',
  'reading_time' => '9 min read',
  'eyebrow' => 'SKILL.md tutorial',
  'h1' => 'How to create a SKILL.md file',
  'lead' => 'This guide shows you how to build an Agent Skill from scratch: the folder layout, how to name it, the YAML frontmatter, the instructions, and a complete example.',
  'sections' => [
    ['heading' => 'Before you start', 'body' => '<p>A SKILL.md file defines an Agent Skill, a packaged capability an AI agent loads only when it is relevant. If you are new to the concept, read <a href="/blog/what-is-skill-md/">what is SKILL.md</a> first. The good news: a working skill needs only one file to begin with. You can add scripts and reference files later.</p><p>Everything here is plain Markdown with a small block of YAML at the top, so you can write it in any text editor and preview it as you go.</p>'],
    ['heading' => 'Where skills live', 'body' => '<p>Agent Skills are stored in a `skills` directory, and the location decides their scope:</p><ul><li><strong>Personal skills:</strong> `~/.claude/skills/` are available across all your projects.</li><li><strong>Project skills:</strong> `.claude/skills/` live in the repo and are shared with your team through Git.</li></ul><p>Each skill is its own folder inside `skills/`, and the SKILL.md file sits directly in that folder. The most common mistake is nesting one level too deep. The path must be `skills/your-skill-name/SKILL.md`, not `skills/your-skill-name/another-folder/SKILL.md`.</p>'],
    ['heading' => 'Step 1: Create and name the skill folder', 'body' => '<p>Make a folder for your skill. The folder name is the skill name, so it has to follow the naming rules:</p><ul><li>Lowercase only, no capitals</li><li>Hyphens between words, no spaces and no underscores</li><li>Up to 64 characters</li><li>Descriptive and specific, for example `pdf-form-filler` or `commit-message-writer`</li></ul><pre><code>.claude/&#10;  skills/&#10;    pdf-form-filler/&#10;      SKILL.md</code></pre><p>Do not put a README.md inside the skill folder. The SKILL.md is the entry point.</p>'],
    ['heading' => 'Step 2: Write the YAML frontmatter', 'body' => '<p>Open SKILL.md and start with a YAML block between two `---` lines. Two fields are required:</p><ul><li><strong>name</strong> must match the folder name exactly (lowercase, hyphen-case, up to 64 characters).</li><li><strong>description</strong> says what the skill does and when to use it. This is the single most important line, because the agent uses it to decide whether to load the skill.</li></ul><pre><code>---&#10;name: pdf-form-filler&#10;description: Fill, flatten, and extract fields from PDF forms. Use when the user works with .pdf forms or asks to fill a PDF.&#10;---</code></pre><p>Optional fields let you control behavior, such as `allowed-tools` to restrict which tools the skill may use, which acts as a permission boundary.</p>'],
    ['heading' => 'Step 3: Write the instructions', 'body' => '<p>Below the frontmatter, write the Markdown body. This is what the agent reads once the skill is triggered. Keep it clear and operational: explain the workflow, the steps, and any rules, and include short examples.</p><pre><code># PDF Form Filler&#10;&#10;## Instructions&#10;1. Identify the form fields in the PDF.&#10;2. Map the user data to each field.&#10;3. Fill the fields, then flatten the file.&#10;&#10;## Examples&#10;- "Fill this PDF with the values in data.json"&#10;- "List the fields in form.pdf"&#10;&#10;## Notes&#10;- Never overwrite the original; save a copy.</code></pre><p>Keep SKILL.md focused. Aim to stay under about 500 lines and move long reference material into separate files.</p>'],
    ['heading' => 'Step 4: Add supporting files (optional)', 'body' => '<p>When a skill needs more than instructions, add folders next to SKILL.md and reference them from the body:</p><ul><li><strong>scripts/</strong> for executable code the agent can run for deterministic steps</li><li><strong>references/</strong> for longer documentation, kept under about 200 lines per file</li><li><strong>templates/</strong> for file templates the skill fills in</li><li><strong>assets/</strong> for static files like images or fonts</li></ul><pre><code>pdf-form-filler/&#10;  SKILL.md&#10;  scripts/&#10;    fill.py&#10;  references/&#10;    field-types.md&#10;  templates/&#10;    output.json</code></pre><p>These files load only when needed, which keeps the skill lightweight at startup.</p>'],
    ['heading' => 'What a complete SKILL.md looks like', 'body' => '<pre><code>---&#10;name: commit-message-writer&#10;description: Write clear, conventional Git commit messages from a diff. Use when the user asks to write or improve a commit message.&#10;allowed-tools: ["Bash", "Read"]&#10;---&#10;&#10;# Commit Message Writer&#10;&#10;## Instructions&#10;1. Read the staged diff with `git diff --cached`.&#10;2. Summarize the change in one short subject line.&#10;3. Use the Conventional Commits format: type(scope): subject.&#10;4. Add a body only if the change needs explanation.&#10;&#10;## Rules&#10;- Subject under 50 characters, imperative mood.&#10;- Wrap the body at 72 characters.&#10;&#10;## Examples&#10;- feat(auth): add password reset flow&#10;- fix(api): handle empty response body</code></pre><p>That is a fully working skill: a clear name, a trigger description, optional tool limits, and concise instructions.</p>'],
    ['heading' => 'How to name a skill well', 'body' => '<p>The name should read like the job it does. Use a verb-plus-object or a clear noun phrase: `pdf-form-filler`, `release-notes-generator`, `sql-query-explainer`. Avoid vague names like `helper` or `utils`, because the agent and your teammates should understand the skill from its name alone. Remember the folder name and the `name` field must match exactly.</p>'],
    ['heading' => 'Writing a description that triggers reliably', 'body' => '<p>The description is the trigger, so it deserves the most care. State two things: what the skill does, and when to use it. Include the words a user would naturally say. The spec allows a long description (up to 1024 characters), but one or two specific sentences usually work best. Compare a weak and a strong version:</p><ul><li>Weak: "Helps with PDFs."</li><li>Strong: "Fill, flatten, and extract fields from PDF forms. Use when the user works with .pdf forms or asks to fill a PDF."</li></ul><p>The strong version names the actions and the triggers, so the agent loads it at the right moment.</p>'],
    ['heading' => 'Best practices and common mistakes', 'body' => '<ul><li>One skill, one job. Split broad ideas into focused skills.</li><li>Match the folder name to the `name` field exactly.</li><li>Do not nest SKILL.md an extra level deep inside the skill folder.</li><li>Do not add a README.md inside the skill folder.</li><li>Keep SKILL.md under about 500 lines; push detail into `references/`.</li><li>Commit project skills to Git so the whole team gets them.</li><li>Test the trigger by describing a task in the agent\'s own words and checking that the skill activates.</li></ul>'],
    ['heading' => 'Draft and preview your SKILL.md', 'body' => '<p>Because SKILL.md is Markdown with YAML frontmatter, you can write and preview it before you ship it. Use the <a href="/editor/">Markdown Docs online editor</a> to check headings, code blocks, and frontmatter, or <a href="/download/">download Markdown Docs</a> to edit it on Windows with autosave. For the bigger picture, see <a href="/blog/ai-agent-instruction-files-explained/">AI agent instruction files explained</a> and <a href="/blog/common-md-files-for-ai-projects/">common .md files for AI projects</a>.</p>']
  ],
  'sources' => [
    ['label' => 'Anthropic: skill authoring best practices', 'url' => 'https://platform.claude.com/docs/en/agents-and-tools/agent-skills/best-practices', 'note' => 'official authoring guidance.'],
    ['label' => 'Claude Code: extend Claude with skills', 'url' => 'https://code.claude.com/docs/en/skills', 'note' => 'for creating and using skills.'],
    ['label' => 'How to create custom skills (Claude Help Center)', 'url' => 'https://support.claude.com/en/articles/12512198-how-to-create-custom-skills', 'note' => 'step-by-step setup.']
  ],
  'faqs' => [
    ['What is the minimum to create a skill?', 'A single folder with a SKILL.md file inside it. The file needs YAML frontmatter with a name and description, plus Markdown instructions. You can add scripts and reference files later.'],
    ['How do I name a skill?', 'Use lowercase hyphen-case, no spaces or underscores, up to 64 characters, and make it descriptive. The folder name must match the name field in the frontmatter exactly.'],
    ['Where do I put the SKILL.md file?', 'In a skill folder under your skills directory: ~/.claude/skills/your-skill/SKILL.md for personal skills, or .claude/skills/your-skill/SKILL.md for project skills.'],
    ['What is the most common mistake?', 'Nesting the file one level too deep. The path must be skills/your-skill/SKILL.md, not skills/your-skill/another-folder/SKILL.md. Also avoid putting a README.md inside the skill folder.'],
    ['How important is the description field?', 'It is the most important field. The agent uses it as the trigger to decide when to load the skill, so it should state clearly what the skill does and when to use it.']
  ]
];

include __DIR__ . '/../../includes/article-template.php';
